### ISSUE TITLE
_renderDownload function is missing

### ISSUE THREAD

**Issue by deltab** [SymfonyContrib/FileFieldBundle#1]
When I try to upload a file, I get a JavaScript error "TypeError: that._renderDownload is not a function", and the preview does not appear. There are two calls to it in jquery.filefield-ui.js, but no definition of it there or anywhere else.

Upstream does have it: https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-ui.js#L508
but it's not present at https://github.com/SymfonyContrib/FileFieldBundle/blob/master/Resources/public/js/jquery.filefield-ui.js#L390.

**Comment by dragonwize** [comment]
The bundle only works with the included version ATM.

**Comment by deltab** [comment]
That's the version I'm using. So is there no way to get it to work at present?

**Comment by deltab** [comment]
I'm using the included version, I mean.

**Comment by dragonwize** [comment]
Then there is something different about how you have set it up. I use this version on many sites and have never gotten that error. Can you post what you have done for setup?

**Comment by deltab** [comment]
Yes, I figured it had to be an obscure code path or someone would've run into it before.

I followed the instructions in https://github.com/SymfonyContrib/FileFieldBundle/blob/master/README.md: installed using composer, added the bundle to AppKernel, added the script links to the relevant templates, did the same for ImageFieldBundle, installed the assets, and changed a form input to 'imagefield'.

I've tracked it down: it happens when there's an error uploading, `data.context` is set, and `data.errorThrown` isn't 'abort'. In my case the error is 'Not Found' because I haven't set up a route for `/filefield-upload`.

There's a routing config file for it, but it's not being loaded (doesn't show up in `console debug:router` output). Did I miss a step in the installation, or should the config be found automatically?

**Comment by dragonwize** [comment]
Sorry for the late response, for some reason I didn't get a notification.

Yes, it looks like I forgot to put the routing in the installation instructions.

You simple need to include the bundles routing.yml file as with any other bundle.

```
# app/config/routing.yml
filefield:
    resource: "@FileFieldBundle/Resources/config/routing.yml"
```
